# Generated by Django 4.0.6 on 2022-07-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('hotel_name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.CharField(max_length=70)),
                ('food_name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=70)),
                ('hotel_id', models.CharField(max_length=70)),
                ('owner_id', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=70)),
                ('hotel_id', models.CharField(max_length=70)),
                ('owner_id', models.CharField(max_length=70)),
                ('menu_id', models.CharField(max_length=70)),
            ],
        ),
    ]
