# Generated by Django 4.1.4 on 2022-12-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("hotel_id", models.IntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("image", models.CharField(max_length=30, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                ("category_id", models.IntegerField(default=1)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("hotel_id", models.IntegerField()),
                ("price", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FoodOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=70)),
                ("item_id", models.CharField(max_length=30)),
                ("h_table_id", models.IntegerField()),
                ("hotel_id", models.IntegerField()),
                ("quantity", models.IntegerField(default=1)),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("rate", models.IntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HotelOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("hotel_name", models.CharField(max_length=70)),
                ("email", models.EmailField(max_length=70)),
                ("password", models.CharField(max_length=70)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HotelTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_name", models.CharField(max_length=70)),
                (
                    "description",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                ("hotel_id", models.IntegerField()),
                ("status", models.IntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=70)),
                (
                    "qr_code_data",
                    models.CharField(blank=True, max_length=70, null=True),
                ),
                ("_from", models.CharField(max_length=30, null=True)),
                ("_to", models.CharField(max_length=30, null=True)),
                ("order_id", models.CharField(max_length=70)),
                ("h_table_id", models.IntegerField()),
                ("hotel_id", models.IntegerField()),
                ("discount_amt", models.IntegerField(blank=True, null=True)),
                ("tax_amt", models.IntegerField(blank=True, null=True)),
                ("net_amt", models.IntegerField()),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("method", models.CharField(blank=True, max_length=30, null=True)),
                ("ratings", models.IntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                ("feedback", models.CharField(blank=True, max_length=225, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="QrCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("transaction_id", models.CharField(max_length=70)),
            ],
        ),
    ]
