# Generated by Django 4.0.6 on 2022-07-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='FoodItem',
        ),
        migrations.RenameModel(
            old_name='Table',
            new_name='HotelTable',
        ),
    ]
