# Generated by Django 4.0.6 on 2022-07-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_menu_fooditem_rename_table_hoteltable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=70)),
                ('item_id', models.CharField(max_length=30)),
                ('h_table_id', models.CharField(max_length=30)),
                ('hotel_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('rate', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='customer_registration',
            new_name='HotelOwner',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='food_id',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='food_name',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='hoteltable',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='hoteltable',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='category_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hoteltable',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='hotel_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hoteltable',
            name='description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='hoteltable',
            name='hotel_id',
            field=models.IntegerField(),
        ),
    ]
