# Generated by Django 4.0.6 on 2022-07-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_foodorder_rename_customer_registration_hotelowner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('hotel_id', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=70)),
                ('qr_code_data', models.CharField(blank=True, max_length=70, null=True)),
                ('_from', models.CharField(max_length=30, null=True)),
                ('_to', models.CharField(max_length=30, null=True)),
                ('order_id', models.IntegerField()),
                ('h_table_id', models.IntegerField()),
                ('hotel_id', models.IntegerField()),
                ('discount_amt', models.IntegerField(blank=True, null=True)),
                ('tax_amt', models.IntegerField(blank=True, null=True)),
                ('net_amt', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('method', models.CharField(blank=True, max_length=30, null=True)),
                ('ratings', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=225, null=True)),
                ('feedback', models.CharField(blank=True, max_length=225, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='h_table_id',
            field=models.IntegerField(),
        ),
    ]
