# Generated by Django 4.0.6 on 2022-07-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_super_admin_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='super_admin',
        ),
    ]
