# Generated by Django 4.0.6 on 2022-07-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_registration',
            old_name='company_name',
            new_name='hotel_name',
        ),
    ]
